forecasts:
  first_year: 1993
  last_year: 2022
  months:
    - 3
    - 6
    - 9
    - 12
  ensemble_size: 2

climatology:
  first_year: 1993
  last_year: 2019

domain:
  south_lat: 10
  north_lat: 81
  west_lon: 156
  east_lon: 255

filesystem:
  # Where to put data that will be used to force the model:
#  model_input_data: /work/acr/mom6/nwa12/forecast_input_data
  model_input_data: /work/Dmitry.Dukhovskoy/NEP_input/fcst_forcing
  # Where to put results from the model simulations:
#  model_output_data: /work/acr/mom6/nwa12/forecast_output_data
  model_output_data: /work/Dmitry.Dukhovskoy/run_output/NEP_season_fcst
  # Path to existing daily river files (one file per year, padded):
#  yearly_river_files: /work/acr/mom6/nwa12/glofas/glofas_runoff_{year}.nc
  yearly_river_files: /work/Dmitry.Dukhovskoy/NEP_input/glofas_runoff
  # Path to existing open boundary condition data:
#  open_boundary_files: /work/acr/mom6/nwa12/glorys/updated
  open_boundary_files: /work/Dmitry.Dukhovskoy/NEP_input/glorys_obc
  # Path to monthly averaged temperature and salinity data, will be used for nudging:
#  monthly_data_nudging: /work/acr/glorys/monthly_filled/glorys_monthly_ts_fine_{year}.nc

  # Path to ocean_static file without mask table:
#  ocean_static: /home/Andrew.C.Ross/git/nwa12/data/geography/ocean_static.nc
  ocean_static: /work/Dmitry.Dukhovskoy/NEP_input/topo_grid/ocean_static.nc
  # Path to the nudged analysis simulation that will be used for initial conditions:
#  analysis_history: /archive/acr/fre/NWA/2023_10/NWA12_COBALT_2023_10_nudgets-90d/gfdl.ncrc5-intel22-prod/history/
  analysis_history: /archive/Dmitry.Dukhovskoy/fre/NEP/2024_04
  # Path to model output from individual forecast simulations:
#  forecast_history: /archive/acr/fre/NWA/2023_04/NWA12_forecast_2023-04_{year}-{month:02d}-e{ensemble:02d}/gfdl.ncrc5-intel22-prod/history/
  forecast_history: /archive/Dmitry.Dukhovskoy/fre/NEP/2024_04/NEP_forecast_2024-04_{year}-{month:02d}-e{ensemble:02d}/gfdl.ncrc5-intel22-prod/history/
  # TODO:need to have process_spear_job.sh read the path to place processed SPEAR data from here
