name: nep_climatologybcs
forecasts:
  first_year: 1993
  last_year: 2022
  months:
    - 1
    - 4
    - 7
    - 10
  ensemble_size: 10

climatology:
  first_year: 1993
  last_year: 2019

domain:
  south_lat: 10
  north_lat: 85
  west_lon: 150
  east_lon: 290

filesystem:
  # Where to put data that will be used to force the model:
  model_input_data: /work/Dmitry.Dukhovskoy/NEP_input/fcst_forcing
  # Where to put results from the model simulations:
  model_output_data: /work/Dmitry.Dukhovskoy/run_output/NEP_season_fcst
  # Existing daily river files (one file per year, padded):
  yearly_river_files: /work/Dmitry.Dukhovskoy/NEP_input/glofas_runoff/glofas_hill_dis_runoff_mac_{year}.nc
  # Path to river climatology:
  river_clim_path: /work/Dmitry.Dukhovskoy/NEP_input/glofas_runoff/
  # Path to existing open boundary condition data:
  open_boundary_files: /work/Dmitry.Dukhovskoy/NEP_input/glorys_obc
  # Path to existing open boundary condition data:
  #   open_boundary_files: /work/acr/mom6/nwa12/glorys/updated
  #   # Path to ocean_static file without mask table:
  ocean_static: /work/Dmitry.Dukhovskoy/NEP_input/topo_grid/ocean_static.nc
  # Path to the nudged analysis simulation that will be used for initial conditions:
  analysis_history: /archive/Dmitry.Dukhovskoy/fre/NEP/2024_04
  # Path to model output from individual forecast simulations:
  forecast_history: /archive/Dmitry.Dukhovskoy/fre/NEP/2024_04/NEP_forecast_2024-04_{year}-{month:02d}-e{ensemble:02d}/gfdl.ncrc5-intel22-prod/history/
  # Path to SPEAR extracted monthly fields:
  spear_month_ens: /work/Dmitry.Dukhovskoy/tmp/spear_subset/
  # Path to SPEAR --> MOM6 OB gmapi indices for bilinear interpolation:
  spear_mom_gmapi: /work/Dmitry.Dukhovskoy/NEP_input/spear_obc
  # Path to seasonal forecast output test:
  nep_seasfcst_test: /work/Dmitry.Dukhovskoy/run_output/NEP_season_fcst/test
  # Path to NEP restart fields:
  nep_seas_restart:
  # SPEAR topo and grid ocean_z.static.nc and sea ice static files:
  spear_topo_grid: /work/Dmitry.Dukhovskoy/data/SPEAR
  # temporary spear files subset to NEP domain for deriving OBC, etc:
  nep_spear_subset: /work/Dmitry.Dukhovskoy/tmp/spear_subset/{year}/ens{ens:02d}
 
